### PR TITLE
Initial API setup (Registration, Login, KPI, Attendance, and Reports)

### PR DESCRIPTION
**Pull request by ridhwanrosman1901**
### **Description:**

This pull request includes the initial setup of the project's API with the following features:

1. **User Registration and Login:**
   - Implemented endpoints for user registration and login.
   - Users can create new accounts and log in to access the system.

2. **KPI Management:**
   - Added endpoints to manage Key Performance Indicators (KPIs).
   - Includes functionality to view and add KPIs relevant to staff performance.

3. **Attendance Tracking:**
   - Created endpoints for logging and retrieving attendance records.
   - Allows users to log their attendance and view historical attendance data.

4. **Performance Reports:**
   - Developed endpoints to generate and retrieve performance reports.
   - Users can view and download detailed performance reports based on monthly data.

This initial API setup lays the groundwork for further development of the project. It includes the backend functionality necessary for managing user accounts, KPIs, attendance records, and performance reports.

### CODE REVIEW

**Comment by ridhwanrosman1901** [comment]
**API Process Flowchart for your clarification✨**
API Process Flow

**Comment by ridhwanrosman1901** [comment]
**API Process Flowchart for your clarification✨** 

API Process Flow

**Comment by idlannaz** [comment]
Macam mana usage JWT tu? ade guideline tak?

**Comment by ridhwanrosman1901** [comment]
> Macam mana usage JWT tu? ade guideline tak?

Bila guest login host akan validate dari database, kalau akaun dia wujud, token dikeluarkan, dapat authorization, baru dia boleh access data lain.

**Pull request merged**
